import type { Metadata } from "next";
import { Inter, Tinos, Playfair } from "next/font/google";
import "@/config/fontawesome";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "@/app/globals.css";

// next metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// next fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
const tinosRegular = Tinos({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-tinos-regular",
});
const tinosBold = Tinos({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-tinos-bold",
});
const playfair = Playfair({
  weight: "variable",
  subsets: ["latin"],
  variable: "--font-playfair",
});

// component
export type AuthLayoutProps = {
  children: React.ReactNode[];
};

export default function AuthLayout(props: AuthLayoutProps) {
  return (
    <html
      className={`${inter.variable} ${tinosRegular.variable} ${tinosBold.variable} ${playfair.variable} text-foreground scrollbar-hide bg-background`}
      lang="pt-BR"
    >
      <body className="h-dvh w-full">{props.children}</body>
    </html>
  );
}
