import type { Metadata } from "next";
import React from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type RootLayoutProps = {
  children: React.ReactNode[];
};

export default function RootLayout(props: RootLayoutProps) {
  return (
    <html lang="pt-BR">
      <body className="bg-background">{props.children}</body>
    </html>
  );
}
